### PR TITLE
#1 setup fastlane

### PR DESCRIPTION
**Pull request by NjeriNjoroge**
### Background
PR has the Fastlane setup

### Metadata
- Issue link: https://github.com/intere/ScryfallApiSwift/issues/1

### CODE REVIEW

**Review by intere — CHANGES_REQUESTED** [review]
Nice work!  Though I have a couple of requests.  Could you move fastlane from the `Example` project to the root directory of the project (it will probably require some changes to the Fastfile)
- `mv Example/Fastlane Fastlane`

Also, would you remove 
- `fastlane/report.xml`
- `fastlane/test_output`
and update the `.gitignore` to exclude those two files/folders?

**Comment by intere** [comment]
Why did you close this PR and delete the branch?

**Comment by NjeriNjoroge** [comment]
I'm making another one with the changes. The previous PR didnt git ignore
the Fastlane files

Regards,
Grace Njoroge

**Comment by intere** [comment]
Got it - thanks!

**Pull request closed without merging**
